---
version: "2.1"
services:
    postgres:
        container_name: postgres
        image: postgres:9.6-alpine
        ports:
            - 5432:5432
        volumes:
            - /var/lib/postgresql/data
        healthcheck:
            test: psql --username postgres -c "SELECT COUNT(1) FROM pg_catalog.pg_roles;"
            interval: 30s
            timeout: 10s
            retries: 3
        environment:
            - SERVICE_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=students_db

    redis:
        image: redis:3-alpine
        ports:
            - 6379:6379

    app:
        build: .
        ports:
            - "8888:5000"
        environment:
            - FLASK_APP=app
            - FLASK_ENV=development
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/students_db
        depends_on:
            - postgres
